config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  resources :portfolios
  resources :contacts,  only: [:new, :create]
  resources :topics,  only: [:index]
  resources :blogs, only: [:index, :show, :search] do
    member do
      get :toggle_status
    end
    collection do
  		get 'search'
  	end
  end

  
  mount ActionCable.server => '/cable'
  get 'tags/:tag', to: 'blogs#index', as: :tag
  get 'pages/home'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
  has_many :portfolio_links
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all 
    @portfolios = Portfolio.all
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end


  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:category_id, :name, :description, :image, :link)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<!-- Portfolio-->
  <section class="module" id="portfolio">
    <div class="container">
      <h1 class="section-title">Portfolio</h1>
      <div class="spacer"></div>
      <div class="row row-portfolio-filter m-b-30">
        <div class="col-md-12">
          <ul class="filters h5" id="filters">
            <li><a class="current" href="#" data-filter="*">All</a></li>
            <% @categories.each do |category| %>
            <li><a href="#" data-filter=<%="." + category.name.downcase %>><%= category.name.capitalize%></a></li>
            <%end%>
          </ul>
        </div>
      </div>
      <div class="row row-portfolio row-gutter row-eq-height" data-columns="3">
        <div class="grid-sizer"></div>
        <% @portfolios.each do |portfolio|%>
          <div class="portfolio-item <%= portfolio.category.name.downcase %> undefined">
            <div class="portfolio-wrapper card h-100">
              <%= image_tag "img-1.jpg" if portfolio.image.nil? %>
              <%= image_tag portfolio.image.url, style: " display: block; width: 100%; height: 300px;"%>
              <div class="portfolio-overlay"></div>
              <div class="portfolio-caption">
                <h5 class="portfolio-title"><%= portfolio.name%></h5>
              </div><a class="portfolio-link" href=<%= portfolio.link %> target="_blank"></a>
            </div>
          </div>
        <%end%>
        </div>
      </div>
      <div class="row m-t-40">
        <div class="col-md-12">
          <div class="text-center"><%= link_to "Show more", portfolios_path, class:"btn btn-lg btn-circle btn-shadow btn-white" %></div>
        </div>
      </div>
    </div>
  </section>
  <!-- Portfolio end-->

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @portfolio.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @portfolio.image %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>