config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  resources :portfolios
  resources :contacts,  only: [:new, :create]
  resources :topics,  only: [:index]
  resources :blogs, only: [:index, :show, :search] do
    member do
      get :toggle_status
    end
    collection do
  		get 'search'
  	end
  end

  
  mount ActionCable.server => '/cable'
  get 'tags/:tag', to: 'blogs#index', as: :tag
  get 'pages/home'
  root to: 'pages#home'
end

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blogs</h1>
    <p class="lead blog-description">Created by: Kay Jay</p>
    <%= link_to 'Write a New Blog', 'admin/blog/new', class: "btn btn-primary" if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-lg-4">
  <aside class="widget widget_search">
     <%= form_tag search_blogs_path, method: :get, class: "navbar-form navbar-center", role: "search" do %>
      <p>
        <%=text_field_tag :search, params[:search], class: "form-control", placeholder: "Hit enter to search..." %>
        <%= button_tag("Search", name: nil, class: "search-button") do%>
          <%= fa_icon "search"%>
        <%end%>
      </p>
    <%end%>   
	</aside>
  
  <div class="sidebar">
    <ol class="list-unstyled social-links">
      <li>
        <% @links.each do |link| %>
          <a href=<%= link.url %> target="_blank" ><%= fa_icon link.name%></a>
        <%end%>
      </li>
    </ol>
  </div>
 
  
  <%unless @related_post.nil? %>
    <div class="sidebar">
      <aside class="widget widget_recent_entries_custom">
        <div class="widget-title">
  				<h5>Related Post</h5>
  			</div>
        <ol>
          <% @related_post.each do |blog| %>
            <%if  blog.id != @blog.id %>
              <li class="clearfix"><%= link_to "#{blog.title}", blog_path(blog)%></li>
            <%end%>
          <%end%>
        </ol>
      </aside>
    </div>
  <%end%>

	<div class="sidebar">
		
		<aside class="widget widget_tag_cloud">
			<div class="widget-title">
				<h5><%= fa_icon "tags"%> Tags</h5>
			</div>
			<div class="tagcloud">
			  <% tag_cloud Blog.tag_counts, %w{s m l} do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: css_class %>
        <% end %>
      </div>
		</aside>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center"><span class="copyright"><%= copyright_generator%></span></div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<section class="module-header parallax bg-dark bg-dark-30" style="background-image: url('http://placehold.it/1920x1200');" >
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="h1 m-b-20">Shop Grid</h1>
                <p>Experienced and Friendly.</p>
            </div>
        </div>
    </div>
</section>

app/views/shared/_nav.html.erb
<header class="header header-center undefined">
    <div class="container-fluid">
        <!-- Logos-->
        <div class="inner-header"><%= link_to '', root_path , class:"inner-brand"%> <%= image_tag "logo.png", class: "brand-dark", width: "77px", alt:""%> <%= image_tag "logo-light.png", class: "brand-light", width: "77px", alt: ""%>
                <!-- Or simple text-->
                <!-- Core--></a></div>
        <!-- Navigation-->
        <div class="inner-navigation collapse">
            <div class="inner-navigation-inline">
                <div class="inner-nav">
                    <ul>
                        <li class="menu-item-has-children menu-item-has-mega-menu"><%= link_to "Home", root_path(anchor: 'home')%></li>
                        <li class="menu-item-has-children"><%= link_to "Portfolio", root_path(anchor: 'portfolio')%></li>
                        <li class="menu-item-has-children"><%= link_to "Blog", root_path(anchor: 'blog') %></li>
                        <% if logged_in?(:site_admin)%><li class="menu-item-has-children"><%= link_to "Contact", root_path(anchor: 'contact') %></li><%end%>
                        <li><%= login_helper 'menu-item-has-children' %></li>
                        <% if logged_in?(:site_admin)%> <li class="menu-item-has-children"> <%= link_to "Admin", rails_admin_path %></li><%end%>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Mobile menu-->
        <div class="nav-toggle"><a href="#" data-toggle="collapse" data-target=".inner-navigation"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a></div>
    </div>
</header>

app/views/shared/_pagebreadcrumb.html.erb
<section class="module-page-title">
    <div class="container">
        <div class="row-page-title">
            <div class="page-title-captions">
                <h1 class="h5">Panels polo shirt</h1>
            </div>
            <div class="page-title-secondary">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Shop</a></li>
                    <li class="breadcrumb-item active">Panels polo shirt</li>
                </ol>
            </div>
        </div>
    </div>
</section>

app/views/shared/_pagination.html.erb
<section class="module-sm module-gray">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <nav>
                    <ul class="pagination h4">
                        <%= link_to fa_icon('long-arrow-right'), " ", class: "page-item next"%>
                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                        <li class="page-item"><a class="page-link" href="#">5</a></li>
                        <%= link_to fa_icon('long-arrow-left'), "/ ", class: "page-item prev"%>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>

app/views/shared/_searchfilter.html.erb
<section class="module-sm module-divider-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <select class="form-control m-t-10 m-b-10">
                    <option>Default Sorting</option>
                    <option>Popular</option>
                    <option>Latest</option>
                    <option>Average Price</option>
                    <option>High Price</option>
                    <option>Low Price</option>
                </select>
            </div>
            <div class="col-md-4">
                <select class="form-control m-t-10 m-b-10">
                    <option>Woman</option>
                    <option>Man</option>
                </select>
            </div>
            <div class="col-md-4">
                <select class="form-control m-t-10 m-b-10">
                    <option>All</option>
                    <option>Coats</option>
                    <option>Jackets</option>
                    <option>Dresses</option>
                    <option>Jumpsuits</option>
                    <option>Tops</option>
                </select>
            </div>
        </div>
    </div>
</section>

app/views/shared/_submenu.html.erb
<div class="off-canvas-sidebar">
    <div class="off-canvas-sidebar-wrapper">
        <div class="off-canvas-header"><a class="close-offcanvas" href="#"><span class="arrows arrows-arrows-remove"></span></a></div>
        <div class="off-canvas-content">
            <!-- Text widget-->
            <aside class="widget widget_text">
                <div class="textwidget">
                    <p class="text-center"><img src="assets/images/logo-light.png" width="100" alt=""></p>
                </div>
            </aside>
            <!-- Text widget-->
            <aside class="widget widget_text">
                <div class="textwidget">
                    <p class="text-center"><img src="assets/images/offcanvas.jpg" alt=""></p>
                </div>
            </aside>
            <!-- Navmenu widget-->
            <aside class="widget widget_nav_menu">
                <ul class="menu">
                    <li class="menu-item menu-item-has-children"><a href="#">Home</a></li>
                    <li class="menu-item"><a href="#">About Us</a></li>
                    <li class="menu-item"><a href="#">Services</a></li>
                    <li class="menu-item"><a href="#">Portfolio</a></li>
                    <li class="menu-item"><a href="#">Blog</a></li>
                    <li class="menu-item"><a href="#">Shortcodes</a></li>
                </ul>
            </aside>
            <ul class="social-icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-vk"></i></a></li>
            </ul>
        </div>
    </div>
</div>