config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  resources :portfolios
  resources :contacts,  only: [:new, :create]
  resources :topics,  only: [:index]
  resources :blogs, only: [:index, :show, :search] do
    member do
      get :toggle_status
    end
    collection do
  		get 'search'
  	end
  end

  
  mount ActionCable.server => '/cable'
  get 'tags/:tag', to: 'blogs#index', as: :tag
  get 'pages/home'
  root to: 'pages#home'
end

app/views/pages/home.html.erb
<!-- Wrapper-->
<div class="wrapper">

  <!-- Page Header-->
  <section class="module-header parallax bg-dark bg-dark-30" data-background=<%= image_url("israel-palacio-459693-unsplash.jpg")%> id="home">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 m-b-20">Kay Jay</h1>
          <p>Experienced and Friendly.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Header end-->

  <!-- Portfolio-->
  <section class="module" id="portfolio">
    <div class="container">
      <h1 class="section-title">Portfolio</h1>
      <div class="spacer"></div>
      <div class="row row-portfolio-filter m-b-30">
        <div class="col-md-12">
          <ul class="filters h5" id="filters">
            <li><a class="current" href="#" data-filter="*">All</a></li>
            <% @categories.each do |category| %>
            <li><a href="#" data-filter=<%="." + category.name.downcase %>><%= category.name.capitalize%></a></li>
            <%end%>
          </ul>
        </div>
      </div>
      <div class="row row-portfolio row-gutter row-eq-height" data-columns="3">
        <div class="grid-sizer"></div>
        <% @portfolios.each do |portfolio|%>
          <div class="portfolio-item <%= portfolio.category.name.downcase %> undefined">
            <div class="portfolio-wrapper card h-100">
              <%= image_tag "img-1.jpg" if portfolio.image.nil? %>
              <%= image_tag portfolio.image.url, style: " display: block; width: 100%; height: 300px;"%>
              <div class="portfolio-overlay"></div>
              <div class="portfolio-caption">
                <h5 class="portfolio-title"><%= portfolio.name%></h5>
                <% if portfolio.portfolio_links.present? %>
                <h5>Listen to it on</h5>
                  <ol class="list-unstyled social-links">
                    <li>
                      <% portfolio.portfolio_links.each do |link| %>
                        <a href=<%= link.url %> target="_blank" ><%= fa_icon link.name%></a>
                      <%end%>
                    </li>
                  </ol>
                <%end%>
              </div><% if portfolio.portfolio_links.empty? %><a class="portfolio-link" href=<%= portfolio.link %> target="_blank"></a><%end%>
            </div>
          </div>
        <%end%>
        </div>
      </div>
      <div class="row m-t-40">
        <div class="col-md-12">
          <div class="text-center"><%= link_to "Show more", portfolios_path, class:"btn btn-lg btn-circle btn-shadow btn-white" %></div>
        </div>
      </div>
    </div>
  </section>
  <!-- Portfolio end-->


  <!-- blog-->
  <section class="module" id="blog">
    <div class="container">
      <h1 class="section-title">Blogs</h1>
      <div class="spacer"></div>
        <div class="row">
          <!-- Content-->
          <div class="col-lg-8 m-auto">
            <!-- Post-->
            <% @blogs.each do |blog|%>
              <article class="post">
                <div class="post-preview">
                <div class="blog-cover" style='background: url(<%= blog.image%>); background-repeat: no-repeat;
                  background-size: 100% 100%;'>
    
                <a href="#"><img src="assets/images/blog/1.jpg" alt=""></a></div>
                <div class="post-wrapper">
                  <div class="post-header">
                    <h2 class="post-title"><%= link_to blog.name, blog_path(blog) %></h2>
                    <ul class="post-meta h5">
                      <li><%= blog.created_at.strftime(" %B %d, %Y") %></li>
                      <li><%= link_to blog.topic.name, blogs_path(:name => "#{blog.topic.name}")  %></li>
                      <li><a href="#"><%= blog.comments.count%> Comments</a></li>
                    </ul>
                  </div>
                  <div class="post-content">
                    <p><%= markdown blog.body.truncate(100) %></p>
                  </div>
                  <div class="post-more"><%= link_to "Read More", blog_path(blog) %></div>
                </div>
              </article>
              <!-- Post end-->
            <%end%>
          </div>
        </div>
        <div class="row m-t-40">
        <div class="col-md-12">
          <div class="text-center"><%= link_to "Show more", blogs_path, class:"btn btn-lg btn-circle btn-shadow btn-white" %></div>
        </div>
      </div>
      </div>
  </section>
  <!-- Portfolio end-->

  <!-- blog-->
  <% if logged_in?(:site_admin)%>
    <%= render 'contacts/form'%>
  <%end%>
 